GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/64498cc29d8e2d32a2c8fd03

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "080-666-419-123"
}

###
PUT http://localhost:3001/api/persons/64498dee5e33c19eeeb95026
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "080-666-419-123"
}

###
DELETE http://localhost:3001/api/persons/64498dee5e33c19eeeb95026