GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arnau Gomes",
  "number": "0706-527-9144"
}

###
DELETE http://localhost:3001/api/persons/1