GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arnau Gomes",
  "number": "0706-527-9144"
}

###
PUT http://localhost:3001/api/persons/64498dee5e33c19eeeb95026
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "080-666-419-123"
}

###
DELETE http://localhost:3001/api/persons/64498dee5e33c19eeeb95026