GET http://localhost:3003/blogs

###
POST http://localhost:3003/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2tpZSIsImlkIjoiNjQ1MjljYzMwNjlhYTk3NWM0MmVkZWM2IiwiaWF0IjoxNjgzMTM1NzM2LCJleHAiOjE2ODMxMzkzMzZ9.c19pMa16lCqUKpwTWG-2OA8yJ2RnT4TTH7B4InUXlL0

{
  "title": "Lokis deception",
  "author": "Liam Rosenior",
  "url": "http://fantasy_ebook.com/",
  "likes": "50",
  "userId": "64529cc3069aa975c42edec6"
}

###
PUT http://localhost:3003/blogs/6452a470c3e6c8581b3b9907
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2tpZSIsImlkIjoiNjQ1MjljYzMwNjlhYTk3NWM0MmVkZWM2IiwiaWF0IjoxNjgzMTM1NzM2LCJleHAiOjE2ODMxMzkzMzZ9.c19pMa16lCqUKpwTWG-2OA8yJ2RnT4TTH7B4InUXlL0

{
  "title": "Arm of god"
}

###
DELETE  http://localhost:3003/blogs/6452a45fc3e6c8581b3b9901
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2tpZSIsImlkIjoiNjQ1MjljYzMwNjlhYTk3NWM0MmVkZWM2IiwiaWF0IjoxNjgzMTM4OTczLCJleHAiOjE2ODMxNDI1NzN9.AcaWbtGQ7mcgoE38EuXVnFEBVnvdbFxEoMsVVYsKGrY

###
GET http://localhost:3003/users

###
POST http://localhost:3003/users
Content-Type: application/json

{
  "username": "jackie",
  "name": "jack henny",
  "password": "jhenny"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
  "username": "jackie",
  "password": "jhenny"
}